version: "3.8"

services:
  postgres:
    # Зафиксировать версию при релизе
    image: "postgres:latest"
    container_name: "postgres"
    hostname: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    networks:
      - "network"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

networks:
  network:
    driver: "bridge"

volumes:
  postgres-data:
    driver: "local"
